# Introduction {#intro}

We are a zooplankton ecology lab. We study zooplankton and their role in connecting ocean food webs to global biogeochemical cycles. Our research explores how plankton growth, feeding, and waste drive carbon and nutrient fluxes, and how these processes are reshaped by climate stressors like warming, acidification, and wildfire inputs. By linking ecology and biogeochemistry, we aim to understand and predict how ocean ecosystems respond to rapid environmental change.\

Our work is based on statistical thinking, using evidence-based approaches to compare among alternatives for models and management options.

See the next chapter for more detail on our lab culture and philosophy.

## How we meet

Currently, we meet weekly lab meetings and individual meetings with Moira.\

THINK ABOUT STRUCTURE FOR LAB MEETING. Each lab member has their own google doc for their 1:1 meetings with Moira. Prior to each meeting, create your agenda for that meeting there.

## How we give feedback

Feedback, both giving and receiving it, is an important aspect of our lab. Most of the feedback we give and receive is when giving and attending practice talks. We expect feedback to be supportive but constructive.

This [resource from UBC](https://scwrl.ubc.ca/student-resources/learning-strategies-for-communicating-science/how-to-give-and-receive-effective-feedback/) does a really great job of outlining the main points of how to give and receive feedback.

## How we share things (and send them to Moira)

We think it is useful to have standard ways of sharing things. These don't always have to be followed but are a useful guide and will make things easier. When sending material to someone, always make sure to describe what you are sending and try to make it as easy as possible for them to help you. Options like a ReadMe file can work, using comments in Excel or other docs sometimes make it hard to transfer to a coding language.

Taking a project-based approach to organizing your work makes it easier to share and solicit feedback from others, as things tend to be self-contained. Try to keep only 1 working instance of material, and use some form of version control to facilitate this (see recommendations in Wilson et. al paper linked above).

Project management tools in Github are a good way to record and document questions on analyses. Use 'Issues' on github repositories for project-related tasks and problems. Alternatively, make use of a GoogleDoc for each project to record this history, much like you would a lab notebook.

Code: can be shared via Github repositories, or via a dedicated Google Drive folder. For specific questions on problems, please try to create a minimal reproducible example. Ensure that others can run and interact with the material being shared.

Writing: Preferably via GoogleDoc, R Markdown, or Overleaf, but MS Word documents can also be shared. Google docs are particularly useful for collaborative writing, and have the advantage of there only ever being one version (as opposed to files that are sent around via email). Word documents should always have your last name as the first part of the file name (e.g. please no "mythesis.doc").

We also share our institutional knowledge through our slack channel. 'issues' repository.

We maintain a lab Google Drive folder for lab publications, presentations, photos, CVs, etc. Please make use of these so that others in the lab can make fair use of our work. There are also personnel folders for storing material, as well as files for data storage that many will use (i.e Cruises, Procedures...)

## Shared lab resources

Where to find shared resources: - Google Drive - You will be given access to the shared drive during onboarding.

## References

