# Academics {#academics}

This chapter contains information pertaining to lab graduate students enrolled in the Biological Oceanography (BO) program.  

You are responsible for your degree. This means you need to stay on top of program and university deadlines, requirements, etc. See Chapter 14 (University of California: San Diego, Scripps Institution of Oceanography, and Décima Lab Resources) for links to resources.  

The [PhD Student Handbook](https://scripps.ucsd.edu/system/files/2025-01/PH.D.Handbook%202024-25_0.pdf) and [MS Stsudent Handbook] (https://scripps.ucsd.edu/system/files/2025-01/MS%20Handbook%2024-25.pdf) should be the first port of call for information about program requirements, and what needs to be done when.  

Registration: Academic credit registration management at UCSD is done through WebReg. Registration for each quarter takes place about mid-way through the previous quarter (see the university academic calendar for dates). It is critical to register promptly to facilitate faculty and institutional planning (and avoid late registration fees). When registering for each quarter, it may be good to discuss course options with Moira to see if she has any suggestions for your progress. 

See Chapter \@ref(courses) for details of courses available to BO graduate students.  
Course of study should be selected with the program requirements in mind - as always, refer to the [PhD Student Handbook] (https://scripps.ucsd.edu/system/files/2025-01/PH.D.Handbook%202024-25_0.pdf) and [MS Student Handbook] (https://scripps.ucsd.edu/system/files/2025-01/MS%20Handbook%2024-25.pdf) for details.  
  
Most students take many of their core program requirements in the first year. Depending on the timing of course offerings, this will likely extend into the student's second year. 

Research units: If the student is not taking enough courses during a quarter to reach full-time status (12 units), the student will fill up the remainder of available units with research units (SIO 299). The student will develop goals and discuss them with Moira each quarter to guide their research efforts. Note that MS students must complete at least 12 research units leading up to the thesis.


## MS students

The M.S. program is intended to be a two-year program. In the first-year, students will complete a majority, if not all, of their required coursework, and begin working on their research project. In the second year, students will primarily focus on their research project, while completing any remaining required or elective coursework. Students are not required to complete two years (six quarters) of study. It is possible for students to complete all program requirements in a shorter period of time. However, two years is the typical timeframe for
completion.

Thesis Committee: 
Each first-year student is assigned a guidance committee. For BS/MS students, their guidance committee consists of the three members who signed off on their application. MS students are provided their guidance committee in their offer letter. The guidance committee is charged with advising until the student forms their thesis committee. The intent is to provide individualized guidance to students, particularly including advice about courses of study that may reach beyond a single curriculum, while ensuring that core requirements are being satisfied.
Students are expected to meet with their guidance committee to discuss coursework and, if applicable, research direction. First-year students are required to submit the [Quarterly Guidance Committee Meeting Form] (https://scripps.ucsd.edu/system/files/2020-09/Guidance%20Committee%20Quarterly%20Meeting.pdf) to the department’s graduate coordinators. This form serves as a planning tool for the upcoming quarter. Once a student forms their thesis committee, the thesis committee is tasked with providing
guidance and oversight through the completion of the student’s degree program.

Remember, not everything will go to plan and your interests and findings may change. Content of theis proposals is not set in stone and can always be revised with communication and collaboration with the committee. View proposals as items that help you build your scientific products rather than evaluative procedures that need to be checked off.  

## Ph.D. students  

PhD dissertations in the Décima lab tend to comprise chapters that will form ~3 publications. Moira encourages students to think about dissertation chapters as publishable units. In the disseration, these 3 chapters will be accompanied by a general Introduction, and a concluding Synthesis chapter that ties the work presented in the dissertation together under the overarching research theme and goals.  ?

Milestones

### Year 1 Coursework and Departmental Exam

Student completes core coursework. To be in good standing, students must maintain a GPA above 3.0 and successfully pass the departmental exam for their curricular group, which will normally be scheduled during the summer following the first year. Curricular groups specify their own expectations for the first year, which may include identifying an advisor (if the student starts out with a rotating advisor), identifying an initial research project, and possibly completing sufficient research to present results as part of the departmental exam.

### Year 2 Initial Research

At the start of the academic year, the student should work with the advisor to determine objectives for the year. This process can take advantage of information in the SIO Advisor/Advisee Expectations document and can make use of a student-initiated Individual Development Plan. In some curricular groups, students may be expected to complete additional coursework in year 2 (maintaining a GPA above 3.0). As an outcome of the departmental exam, the exam committee might communicate to the student specific recommendations to address identified shortcomings e.g. through additional coursework or supervised projects. Recommendations from the exam committee should be addressed in year 2 in consultation with the advisor and the exam committee. By the end of year 2, a student’s research progress should be sufficient to contribute to the first chapter of their PhD thesis. Students should fulfill the ethics course requirement (usually by taking SIOG232 Ethical and Professional Science or SIOB 273 Professional Ethics in Science).

### Year 3 Advancement to Candidacy (Qualifying)

At the start of the academic year, the student should work with the advisor to determine objectives for the year. Student should form their PhD thesis committee by the end of winter quarter. To be in good standing, the student must qualify by the end of Year 3*. Before qualifying, student should have completed all required coursework, as specified by their curricular group, including fulfilling the ethics course requirement. The qualifying exam requires writing and orally defending (to the PhD committee) a thesis proposal that lays out a research plan for the PhD thesis.

### Year 4 Ongoing Research

At the start of the academic year, the student should work with the advisor to determine objectives for the year. Student should meet with their PhD thesis committee at least once to check on progress since qualifying. By the end of year 4, student 11 will have completed and written up research representing at least half of the material that will appear in the final dissertation. Ideally, this will have been submitted as at least one journal article, and a second article may be in preparation.

### Year 5 Defending

At the start of the academic year, the student should work with the advisor to determine objectives for the year. Student should be well on their way to finalizing their PhD theses (e.g., research for all chapters is complete) at the end of year 5 in preparation for the upcoming defense. We recognize that there may be extenuating circumstances*, and the student’s advisor and the PhD thesis committee can agree to extend the student’s academic timeline beyond year 5 if adequate justification can be provided and if funding is available from the advisor. 

### Pre-Qualifying Guidance Committee

The guidance committee is charged with advising the student during the first year and until the student forms their doctoral committee. The intent is to provide individualized guidance to students, particularly regarding advice about a course of study that may reach beyond a single curricular group. First-year students are expected to meet quarterly with their guidance committee to discuss coursework and, if applicable, research direction. First-year students are required to submit the [Quarterly Guidance Committee Meeting Form] (https://scripps.ucsd.edu/system/files/2024-10/%288%3A24%29Guidance%20Committee%20Quarterly%20Meeting.pdf) to the department’s Graduate Coordinator. This form serves as a planning tool for the upcoming quarter. Starting in year two, students are expected to meet with their guidance committee annually until the student constitutes their doctoral committee. The student and their guidance committee should make every effort to hold a single, in-person meeting. However, if this is not possible, the student can meet separately with individual members of the committee.

### Dissertation Committee

The Doctoral Committee will determine the student's qualifications for independent research by conducting a Qualifying Examination, no later than the end of the student’s third year of study. The Doctoral Committee should be constituted no later than winter quarter of a student’s third year. Doctoral Committees in the Scripps Department consist of 4 members who hold appropriate instructional titles at UC San Diego (see eligibility table). Committee members are chosen from at least two departments, and at least two members must represent
academic specialties that differ from the student’s specialty. This includes one member who is a tenured or Emeritus UC San Diego professor and one member from another UC San Diego department. Generally, 3 members of the committee are from the Scripps Department with at least one
of those members in a curricular group different from the student. The member from another department can have a joint appointment with Scripps if the officially designated home department for their appointment is in a UC San Diego department other than Scripps. Each committee must have a Committee Chair. A Co-Chair may be appointed but is not required, unless the student is advised by an Adjunct Professor. A fifth member can be appointed to a student’s doctoral committee, at the discretion of the student’s Committee Chair(s) and upon approval by the Department Chair and Dean of Graduate Division. A fifth member is typically a second Researcher with a Lecturer’s Appointment or someone who is not eligible to serve as one of the required five members (e.g. Project Scientist or a professor from outside of the UC system). A copy of the fifth member’s CV is required, along with a justification
of the individual’s inclusion on the committee.


### Departmental Exams

At the end of the first year, Ph.D. students are required to take the Departmental Exam which is administered by their curricular group. The Departmental Exam is intended to test the general scientific background of the student, the ability to integrate material from specific courses in analyzing new problems, demonstration of a reasonable degree of originality and insight, and the ability to present clear verbal and/or written arguments. Expectations and format varies with the curricular group. 

### Qualifying Exam

By the end of the third year, PhD students are required to to lay out a research plan that they will tackle for dissertation, to convince a five-person committee that it is worthy of a Ph.D., to demonstrate that the student has the background and tools to carry out the plan and to assess whether it can be completed within normative time. 

There should be some form of written proposal. This should lay out the problem that the student wishes to address, accompanied by a thorough review of the literature to provide context. A tentative outline with a list of proposed chapter titles for the dissertation is helpful, as is a timeline describing the status and the expected date of completion of each part. Each proposal should have publication quality illustrations with captions and a complete bibliography. It should have the look of a ‘real’ proposal typical in the student’s field. As a courtesy to the committee, the student should provide the proposal to the committee members at least three weeks prior to the exam. It is often helpful to discuss it with each committee member in advance.

### Final Defense

The doctoral committee supervises and conducts the oral defense and final examination, which shall be publicly held and so announced. The oral defense must be scheduled during the standard work week, Monday-Friday, and must be held during normal business hours. Defenses can be held in-person, virtually, or a combination of both. The committee chair and “upper campus”member must participate in the defense. One member of the committee, outside of the chair and “upper campus” member, can be absent from the defense. The student will need to make arrangements to present to that member prior to the defense. That member should forward any questions to the committee chair, to be discussed at the defense.


Remember, not everything will go to plan and your interests and findings may change. Content of thesis proposals is not set in stone and can always be revised with communication and collaboration with the committee. View proposals and exams as items that help you build your scientific products rather than evaluative procedures that need to be checked off.  
