# PIC {#PIC}

The Pelagic Invertabrate Collection (PIC) is an amazing resource that we have at Scripps Institution of Oceanography. Moira is the Curator of the collection, and Linsey Sala is the manager of the collection. 

To use samples or gear from the PIC it begins with an official loan request. This should be done through email (not slack). 

The official loan request should include:
  - What samples or gear you are requesting? 
  - What purpose you are using them for? (If this hasn't already been agreed upon this process may be longer)
    - Is it descructive? 
  - About how long will you use them for? 
  - What data or information do you need along with the samples or gear? 
  - Also include an acknoledgment that you will return all samples or gear in the condition they were recieved (unless previously agreed upon) or you will replace (if possible)

Once a loan is approved you will work with Linsey to find a time to collect the samples or gear. Give good notice, Linsey works on many different projects and can't always drop things to help. She is very kind in her flexablity but this should no be taken advantage of. 

Once a loan is done the person who requested the samples or gear is responsbile for returning them. Again find a time to meet with Linsey to discuss anything that may have broken or needs replacement or if samples no longer align with the metadata (Note: this shouldn't be the first time anyone is hearing of missing equipment or lost samples)

