# University of California: San Diego, Scripps Institution of Oceaongraphy, and Décima Lab Resources

## General information about University of California: San Diego and Scripps Institution of Oceanography

The SIO [directory](https://scripps.ucsd.edu/directory) lists all faculty, staff, and students across SIO. This is not updated frequently but may help you in locating a specific person and their contact information.

## University Codes of Conduct

- [UC San Diego Student Conduct Code](https://students.ucsd.edu/sponsor/student-conduct/)
- [Office for the Prevention of Harassment & Discrimination (OPHD)](https://ophd.ucsd.edu/)
- [UC San Diego Principles of Community](https://ucsd.edu/about/principles.html)

## For Graduate Students

- [Scripps Current Students Portal](https://a5.ucsd.edu/tritON/profile/SAML2/Redirect/SSO?execution=e1s1) – orientation, academic requirements, forms, funding resources
- [UCSD Graduate Division](https://grad.ucsd.edu/) – fellowships, TA/RA policies, professional development
- [Scripps Student Resources](https://scripps.ucsd.edu/cur-std/student-resources) – wellness, career support, diversity & inclusion

## For Employees

- [UC San Diego Human Resources](https://blink.ucsd.edu/HR/) – payroll, benefits, employee services
- [Academic Personnel Services](https://aps.ucsd.edu/) – appointments, leaves, promotions
- [Research Compliance & Safety](https://blink.ucsd.edu/research/compliance/) – IRB, IACUC, shipboard safety

---

## Décima Lab Resources

* [Décima Lab website](https://decima.ucsd.edu/)
* Décima Lab Google Drive & Calendar – ask Moira for a link to access & collaborate!
* Lab Slack – day-to-day communications (ask for an invite)
* [Lab publications on Google Scholar](https://scholar.google.com/)

### Weekly Lab Meetings
- For Fall 2025 Tuesdays at 12:00 PM PST
- Location: SIO / Sverdrup Hall or Zoom when remote
