project: 
  type: book
  output-dir: _book

format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 2
    number-sections: true
    code-fold: true
    page-layout: full

book:
  title: "Décima Lab Manual"
  author: "PhD Students 2024-2025, Inspired by Fay Lab and others listed below"
  date: last-modified 
  description: "This is the lab manual for the Décima Lab at the University of California: San Diego, Scripps Institution of Oceanography" 
  
  page-footer:
    left: |
      <a href="http://www.smast.umassd.edu/lab_fay/">The Fay lab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  site-url: https://gracecawley.github.io/decima-lab-manual/
  repo-url: https://github.com/GraceCawley/decima-lab-manual
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-intro-how-we-work.qmd
    - 02-lab-culture-philosophy.qmd
    - 03-code-of-conduct.qmd
    - 04-onboarding.qmd
    - 05-expectations.qmd
    - 06-offboarding.qmd
    - 07-funding.qmd
    - 08-communication.qmd
    - 09-academics.qmd
    - 10-courses.qmd
    - 11-computing.qmd
    - 12-umassd-resources.qmd

bibliography: [references.bib, book.bib]
